"""
The figures in `imgs/`, generated from the library rather than drawn by hand.

Run `python examples/figures.py` to regenerate every PNG the docs reference.

Each `fig_*` function returns `(figure, facts)`. `facts` is the set of numbers
the figure asserts visually - how many samples were flagged, whether the series
changed length, what the band ratio came to. `tests/unit/test_figures.py` calls
the same functions and asserts the same numbers, so a figure cannot quietly
stop matching the library: either the build raises or the claim fails.

That indirection is the point. The three PNGs these replace were committed in
2025-05, referenced by nothing, and regenerated by nothing; by 2026-09 they
predated the whole #20-#108 behaviour arc and no test could tell.

Palette: categorical slots 1/2/3 of the reference data-viz palette, validated
for colour-vision deficiency separation (worst adjacent pair dE 8.4, protan)
and for >= 3:1 contrast against a light surface. Series identity never rests on
colour alone - every series is in the legend, and flagged samples additionally
carry their own marker shape.
"""

import sys
import textwrap
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:          # runnable without installing the package
    sys.path.insert(0, str(ROOT))

from baseTs import baseTs  # noqa: E402

IMGS = ROOT / "imgs"

RAW = "#8a8986"        # context, deliberately recessive
DESPIKED = "#2a78d6"   # categorical 1 - the processed signal
FLAGGED = "#eb6834"    # categorical 2 - what the filter caught
FIT = "#199e70"        # categorical 3 - the LOWESS fit
INK = "#0b0b0b"
MUTED = "#52514e"

FS = 100.0
SPIKES = np.array([120, 275, 410, 455, 700, 830, 915])
SPIKE_AMPS = np.array([6.0, -5.0, 7.0, 5.5, -6.0, 6.5, -5.5])
GAP = slice(600, 640)


def _signal(with_gap=False, seed=3):
    """A 10 s, 100 Hz signal: two slow components, noise, and planted spikes."""
    rng = np.random.RandomState(seed)
    t = np.arange(0, 10, 1 / FS)
    clean = np.sin(2 * np.pi * 0.5 * t) + 0.3 * np.sin(2 * np.pi * 1.5 * t)
    sig = clean + 0.08 * rng.randn(len(t))
    sig[SPIKES] += SPIKE_AMPS
    if with_gap:
        sig[GAP] = np.nan
    return t, sig


def _style(ax):
    """Recessive grid and axes; the data carries the ink."""
    ax.grid(True, color="#e3e2df", linewidth=0.6)
    ax.set_axisbelow(True)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color("#c9c8c4")
    ax.tick_params(colors=MUTED, labelsize=8)


def fig_despiking():
    """
    What `filter_outliers()` actually does: flags samples and *replaces* them.

    One axes, so raw and despiked share a y-scale and the reader can see the
    size of the correction. The flagged samples are marked on the raw trace -
    the decision is the thing being illustrated, not the before/after. The
    zoom panel separates the two halves of the operation, which is what most
    readers get wrong: the LOWESS fit *detects* the outlier, and the flagged
    sample is then replaced by linear interpolation between its neighbours -
    it lands near the fit, not on it, and it is never dropped.
    """
    t, sig = _signal()
    ts = baseTs(sig, t, freq=FS, signal_name="demo")
    ts.set_outlier_filter(z_threshold=3.0, frac=0.075)
    despiked = ts.filter_outliers()

    flagged = np.asarray(despiked.outlier_indices, dtype=int)
    raw_v = np.asarray(ts, float)
    out_v = np.asarray(despiked, float)
    fit = np.asarray(despiked.lowess_fit, float)

    # The fit detects; interpolation replaces. Measured, not assumed: none of
    # the replacements equals the fit, and each equals a linear interpolation
    # between its nearest unflagged neighbours.
    unflagged = np.setdiff1d(np.arange(len(out_v)), flagged)
    lin = np.interp(flagged, unflagged, out_v[unflagged])

    facts = {
        "n_total": len(ts),
        "n_flagged": len(flagged),
        "n_changed": int((raw_v != out_v).sum()),
        "n_nan_after": int(np.isnan(out_v).sum()),
        "len_unchanged": len(ts) == len(despiked),
        "planted_all_caught": bool(np.isin(SPIKES, flagged).all()),
        "n_replacements_equal_to_fit": int(np.isclose(out_v[flagged], fit[flagged]).sum()),
        "replacements_are_linear_interp": bool(np.allclose(out_v[flagged], lin)),
    }

    peak = int(SPIKES[2])
    lo, hi = peak - 20, peak + 20

    fig, (ax, axz) = plt.subplots(
        1, 2, figsize=(11, 4.2), width_ratios=[3, 1], layout="constrained")

    # Left: the whole series, one y-axis, so the correction is not a rescale.
    ax.axvspan(t[lo], t[hi - 1], color="#eceaf6", zorder=0)
    ax.plot(t, raw_v, color=RAW, linewidth=1.0, label="Raw", zorder=1)
    ax.plot(t, out_v, color=DESPIKED, linewidth=1.6, label="Despiked", zorder=3)
    ax.plot(t[flagged], raw_v[flagged], linestyle="none", marker="o",
            markersize=5.5, markerfacecolor="none", markeredgecolor=FLAGGED,
            markeredgewidth=1.4, label=f"Flagged ({len(flagged)})", zorder=4)
    _style(ax)
    ax.set_ylim(raw_v.min() - 0.6, raw_v.max() + 2.4)   # headroom for the legend
    ax.set_title("filter_outliers() flags samples and replaces them",
                 fontsize=12, color=INK, loc="left")
    ax.set_xlabel("Time (s)", fontsize=9, color=MUTED)
    ax.set_ylabel("Amplitude", fontsize=9, color=MUTED)
    ax.legend(loc="upper right", frameon=False, fontsize=8, ncol=3)
    ax.text(0.0, -0.19,
            f"{facts['n_flagged']} of {facts['n_total']} samples flagged and replaced  ·  "
            f"length unchanged ({len(ts)} -> {len(despiked)})  ·  "
            f"{facts['n_nan_after']} NaN introduced",
            transform=ax.transAxes, fontsize=8.5, color=MUTED)

    # Right: the shaded slice, expanded. Clipped to the despiked range so the
    # replacement is legible - the raw spike leaves the frame and is labelled.
    axz.plot(t[lo:hi], raw_v[lo:hi], color=RAW, linewidth=1.2, label="Raw")
    axz.plot(t[lo:hi], fit[lo:hi], color=FIT, linewidth=1.8, linestyle="--",
             label="LOWESS fit (detects)")
    axz.plot(t[lo:hi], out_v[lo:hi], color=DESPIKED, linewidth=1.8, label="Despiked")
    axz.plot(t[peak], out_v[peak], marker="o", markersize=6, color=DESPIKED,
             markeredgecolor="white", markeredgewidth=1.0, zorder=5)
    local = out_v[lo:hi]
    pad = max(0.35, 0.45 * (local.max() - local.min()))
    axz.set_ylim(local.min() - pad, local.max() + pad)
    axz.annotate(f"raw {raw_v[peak]:.1f} ↑", xy=(t[peak], axz.get_ylim()[1]),
                 xytext=(0, -12), textcoords="offset points", ha="center",
                 fontsize=7.5, color=FLAGGED)
    _style(axz)
    axz.set_title("the shaded slice, expanded", fontsize=9.5, color=INK, loc="left")
    axz.set_xlabel("Time (s)", fontsize=9, color=MUTED)
    axz.legend(loc="lower right", frameon=False, fontsize=7.5)
    axz.text(0.0, -0.19,
             "flagged by the fit, replaced by interpolation\n"
             "between neighbours — near the fit, not on it",
             transform=axz.transAxes, fontsize=8.5, color=MUTED)
    return fig, facts


def fig_gap_order():
    """
    Why `interpolate_gaps()` has to come first.

    `filter_outliers()` only interpolates the samples *it* flags. A real
    acquisition dropout survives it untouched, and the Butterworth filters then
    refuse the series. The top two panels share a y-axis so the despiking is
    visible as a correction rather than as a rescale.
    """
    t, sig = _signal(with_gap=True)
    ts = baseTs(sig, t, freq=FS, signal_name="demo")
    ts.set_outlier_filter(z_threshold=3.0, frac=0.075)
    despiked = ts.filter_outliers()

    try:
        despiked.lowpass_filter(cutoff=3.0)
        raised, message = False, ""
    except ValueError as exc:
        raised, message = True, str(exc)

    filled = despiked.interpolate_gaps()
    out = filled.lowpass_filter(cutoff=3.0)

    facts = {
        "n_nan_raw": int(np.isnan(sig).sum()),
        "n_nan_after_despike": int(np.isnan(np.asarray(despiked, float)).sum()),
        "n_nan_after_interpolate": int(np.isnan(np.asarray(filled, float)).sum()),
        "filter_raised_on_gap": raised,
        "message": message,
    }

    fig, axes = plt.subplots(3, 1, figsize=(10, 7.2), sharex=True,
                             layout="constrained")
    gap_t = (t[GAP.start], t[GAP.stop - 1])

    for ax in axes:
        _style(ax)
        ax.axvspan(*gap_t, color="#f2e4de", zorder=0)

    axes[0].plot(t, sig, color=RAW, linewidth=1.1, label="Raw")
    axes[0].set_title("1 · Raw — planted spikes, plus a 0.4 s dropout (shaded)",
                      fontsize=10, color=INK, loc="left")

    axes[1].plot(t, np.asarray(despiked, float), color=DESPIKED,
                 linewidth=1.4, label="After filter_outliers()")
    axes[1].set_title(
        f"2 · After filter_outliers() — spikes replaced, "
        f"but {facts['n_nan_after_despike']} NaN remain in the dropout",
        fontsize=10, color=INK, loc="left")
    axes[1].sharey(axes[0])   # the correction, not a rescale

    axes[2].plot(t, np.asarray(out, float), color=FIT, linewidth=1.6,
                 label="interpolate_gaps() → lowpass_filter(3 Hz)")
    axes[2].margins(y=0.30)
    axes[2].set_title("3 · interpolate_gaps() first, then the filter runs",
                      fontsize=10, color=INK, loc="left")
    axes[2].set_xlabel("Time (s)", fontsize=9, color=MUTED)

    for ax in axes:
        ax.legend(loc="upper right", frameon=False, fontsize=8)
        ax.set_ylabel("Amplitude", fontsize=9, color=MUTED)

    if raised:
        wrapped = textwrap.fill(f"ValueError: {message}", 58)
        axes[1].text(
            0.012, 0.05,
            "lowpass_filter() on this series raises:\n" + wrapped,
            transform=axes[1].transAxes, fontsize=7.5, color="#8c2f12",
            family="monospace", va="bottom",
            bbox=dict(boxstyle="round,pad=0.45", facecolor="#fdf1ec",
                      edgecolor="#e8c4b4", linewidth=0.8))
    return fig, facts


def _long_signal(duration=60.0, seed=3):
    """
    The same signal shape over a longer record.

    Frequency resolution is 1/duration, so the 10 s signal the other figures
    use gives 0.1 Hz bins and draws its peaks as triangles. 60 s gives 0.017 Hz
    and a spectrum worth looking at.
    """
    rng = np.random.RandomState(seed)
    t = np.arange(0, duration, 1 / FS)
    sig = (np.sin(2 * np.pi * 0.5 * t) + 0.3 * np.sin(2 * np.pi * 1.5 * t)
           + 0.08 * rng.randn(len(t)))
    spikes = np.arange(120, len(t), 971)
    sig[spikes] += 6.0 * np.where(np.arange(len(spikes)) % 2, -1.0, 1.0)
    return t, sig


def fig_band_power():
    """
    `relative_band_power()` against the null it should be read against.

    The shaded band is the numerator. The strip underneath puts the ratio next
    to the bin fraction - what an equal-power (white-noise) series of the same
    length would score - because a band ratio means very little on its own, and
    `BandPowerResult` already carries the baseline.
    """
    t, sig = _long_signal()
    ts = baseTs(sig, t, freq=FS, signal_name="demo")
    ts.set_outlier_filter(z_threshold=3.0, frac=0.075)
    clean = ts.filter_outliers()

    low, high = 0.3, 0.8
    res = clean.relative_band_power(low, high, details=True)
    freqs, power = clean.get_frequency_content()
    freqs, power = np.asarray(freqs, float), np.asarray(power, float)

    facts = {
        "ratio": float(res.ratio),
        "bin_fraction": float(res.bin_fraction),
        "n_band_bins": int(res.n_band_bins),
        "n_total_bins": int(res.n_total_bins),
        "low_freq": float(res.low_freq),
        "high_freq": float(res.high_freq),
        "freq_resolution": float(res.freq_resolution),
        "above_null": float(res.ratio) > float(res.bin_fraction),
    }

    view = freqs <= 2.5
    fig, (ax, axb) = plt.subplots(
        2, 1, figsize=(10, 5.2), height_ratios=[4, 1], layout="constrained")

    ax.axvspan(low, high, color="#dce9f8", zorder=0,
               label=f"Band {low}–{high} Hz ({res.n_band_bins} bins)")
    ax.plot(freqs[view], power[view], color=DESPIKED, linewidth=1.6,
            label="Power spectrum")
    _style(ax)
    ax.set_xlim(0, 2.5)
    ax.set_title("relative_band_power() — the band, and the null to read it against",
                 fontsize=12, color=INK, loc="left")
    ax.set_xlabel("Frequency (Hz)", fontsize=9, color=MUTED)
    ax.set_ylabel("Power", fontsize=9, color=MUTED)
    ax.legend(loc="upper right", frameon=False, fontsize=8)

    # Both quantities are fractions of total power, so they share one axis.
    axb.barh([1, 0], [res.ratio, res.bin_fraction], height=0.55,
             color=[DESPIKED, RAW])
    axb.set_yticks([1, 0])
    axb.set_yticklabels(["measured ratio", "white-noise null"], fontsize=8.5)
    axb.set_xlim(0, 1)
    axb.set_xlabel("Fraction of total power", fontsize=9, color=MUTED)
    _style(axb)
    axb.grid(axis="y", visible=False)
    for y, v in ((1, res.ratio), (0, res.bin_fraction)):
        axb.text(v + 0.012, y, f"{v:.3f}", va="center", fontsize=8.5, color=INK)
    axb.text(1.0, 1.55, f"{res.n_band_bins} of {res.n_total_bins} bins  ·  "
                        f"resolution {res.freq_resolution:.3f} Hz",
             ha="right", fontsize=8, color=MUTED, transform=axb.get_yaxis_transform())
    return fig, facts


FIGURES = {
    "despiking": fig_despiking,
    "gap_order": fig_gap_order,
    "band_power": fig_band_power,
}


def main():
    IMGS.mkdir(exist_ok=True)
    for name, build in FIGURES.items():
        fig, facts = build()
        path = IMGS / f"{name}.png"
        fig.savefig(path, dpi=110)
        plt.close(fig)
        print(f"{path.relative_to(IMGS.parent)}: {facts}")


if __name__ == "__main__":
    import matplotlib
    matplotlib.use("Agg")
    main()
