"""
The figures in `imgs/` are claims, so they are tested like claims.

`examples/figures.py` returns, alongside each figure, the numbers that figure
asserts visually. This module calls the same builders and asserts the same
numbers. A library change that falsifies a figure therefore fails here rather
than leaving a stale PNG in the README.

Two guards matter as much as the numeric ones:

* `test_no_orphaned_images` - every PNG in `imgs/` is produced by a builder.
  The three images this suite replaced were committed in 2025-05 and
  referenced and regenerated by nothing; by 2026-09 they predated the whole
  #20-#108 behaviour arc and no test could tell.
* `test_every_figure_is_referenced` - and every one is actually shown in the
  docs, which is the other half of how the previous set rotted.
"""

import importlib.util
import re
import warnings
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import pytest  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
IMGS = ROOT / "imgs"
DOCS_THAT_SHOW_FIGURES = (ROOT / "README.md", ROOT / "docs" / "EXAMPLES.md")


def _load_figures_module():
    """`examples/` is deliberately not a package - it must not be installed."""
    path = ROOT / "examples" / "figures.py"
    spec = importlib.util.spec_from_file_location("_basets_figures", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


figures = _load_figures_module()


@pytest.fixture(autouse=True)
def _close_figures():
    yield
    plt.close("all")


@pytest.fixture(scope="module")
def built():
    """Every figure, built once. A build that warns is a build that fails."""
    out = {}
    for name, build in figures.FIGURES.items():
        with warnings.catch_warnings():
            warnings.simplefilter("error")
            fig, facts = build()
        out[name] = facts
        plt.close(fig)
    return out


@pytest.mark.parametrize("name", sorted(figures.FIGURES))
def test_every_figure_builds_without_warning(name):
    with warnings.catch_warnings():
        warnings.simplefilter("error")
        fig, facts = figures.FIGURES[name]()
    assert fig.get_axes(), f"{name} produced no axes"
    assert facts, f"{name} asserted nothing"
    plt.close(fig)


class TestDespikingFigure:
    """filter_outliers() flags, then replaces. Both halves are drawn."""

    def test_the_planted_spikes_are_all_caught(self, built):
        f = built["despiking"]
        assert f["planted_all_caught"], "the figure shows spikes the filter missed"
        assert 0 < f["n_flagged"] < f["n_total"]

    def test_replacement_not_removal(self, built):
        """The caption's central claim: nothing is dropped, nothing goes NaN."""
        f = built["despiking"]
        assert f["len_unchanged"]
        assert f["n_nan_after"] == 0

    def test_every_changed_sample_is_a_flagged_sample(self, built):
        f = built["despiking"]
        assert f["n_changed"] == f["n_flagged"]

    def test_the_fit_detects_and_interpolation_replaces(self, built):
        """
        The distinction the zoom panel is drawn to make, and the one an earlier
        draft of that panel got backwards: the LOWESS fit drives detection, but
        a flagged sample is replaced by linear interpolation between its
        nearest unflagged neighbours - landing near the fit, never on it.
        """
        f = built["despiking"]
        assert f["replacements_are_linear_interp"]
        assert f["n_replacements_equal_to_fit"] == 0


class TestGapOrderFigure:
    """Why interpolate_gaps() has to precede the Butterworth filters."""

    def test_filter_outliers_leaves_a_real_dropout_alone(self, built):
        f = built["gap_order"]
        assert f["n_nan_raw"] > 0
        assert f["n_nan_after_despike"] == f["n_nan_raw"]

    def test_the_filter_refuses_the_gappy_series(self, built):
        f = built["gap_order"]
        assert f["filter_raised_on_gap"], "panel 2's error box would be fiction"
        assert "NaN" in f["message"]

    def test_interpolate_gaps_clears_them(self, built):
        assert built["gap_order"]["n_nan_after_interpolate"] == 0


class TestBandPowerFigure:
    """A band ratio is only readable against its null."""

    def test_the_ratio_beats_the_white_noise_null(self, built):
        f = built["band_power"]
        assert f["above_null"]
        assert 0.0 <= f["bin_fraction"] <= f["ratio"] <= 1.0

    def test_the_bin_counts_are_consistent(self, built):
        f = built["band_power"]
        assert 0 < f["n_band_bins"] < f["n_total_bins"]
        assert f["low_freq"] < f["high_freq"]

    def test_the_resolution_is_worth_plotting(self, built):
        """
        The first draft ran on the 10 s signal, whose 0.1 Hz bins drew the peaks
        as triangles - the same artefact as the figures this set replaced.
        """
        assert built["band_power"]["freq_resolution"] < 0.05


def test_no_orphaned_images():
    """Every PNG in imgs/ comes from a builder. No strays, no leftovers."""
    on_disk = {p.stem for p in IMGS.glob("*.png")}
    produced = set(figures.FIGURES)
    assert on_disk == produced, (
        f"imgs/ and examples/figures.py disagree - "
        f"orphaned: {sorted(on_disk - produced)}, missing: {sorted(produced - on_disk)}"
    )


@pytest.mark.parametrize("name", sorted(figures.FIGURES))
def test_every_figure_is_referenced_by_the_docs(name):
    """A figure nothing displays is a figure nothing keeps honest."""
    shown = "\n".join(p.read_text(encoding="utf-8") for p in DOCS_THAT_SHOW_FIGURES)
    assert re.search(rf"imgs/{name}\.png", shown), (
        f"imgs/{name}.png is not referenced by "
        f"{[p.name for p in DOCS_THAT_SHOW_FIGURES]}"
    )


@pytest.mark.parametrize("name", sorted(figures.FIGURES))
def test_the_committed_png_exists(name):
    path = IMGS / f"{name}.png"
    assert path.exists(), f"run `python examples/figures.py` to regenerate {path.name}"
    assert path.stat().st_size > 10_000, f"{path.name} looks truncated"
